# GNU Make project makefile autogenerated by GENie

.SUFFIXES:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(MAKESHELL)))
  SHELLTYPE := posix
endif

ifeq (posix,$(SHELLTYPE))
  MKDIR = $(SILENT) mkdir -p "$(1)"
  COPY  = $(SILENT) cp -fR "$(1)" "$(2)"
  RM    = $(SILENT) rm -f "$(1)"
else
  MKDIR = $(SILENT) mkdir "$(subst /,\\,$(1))" 2> nul || exit 0
  COPY  = $(SILENT) copy /Y "$(subst /,\\,$(1))" "$(subst /,\\,$(2))"
  RM    = $(SILENT) del /F "$(subst /,\\,$(1))" 2> nul || exit 0
endif

CC  = gcc
CXX = g++
AR  = ar

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

MAKEFILE = OlcTemplate.make

ifeq ($(config),debug)
  OBJDIR              = obj/Debug
  TARGETDIR           = bin/Debug
  TARGET              = $(TARGETDIR)/OlcTemplate
  DEFINES            +=
  INCLUDES           += -I".." -I"../sdk/box2d/include" -I"../sdk/imgui-1.90.4" -I"../sdk/imgui-1.90.4/backends" -I"../sdk/sol2-3.3.0" -I"../sdk/lua-5.4.2/include" -I"../sdk/soloud/include" -I"../sdk/freetype-2.13.1/include" -I"../../../../../usr/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -std=c++2a
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -std=c++2a
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../../../usr/lib" -L"../sdk/box2d/linux" -L"../sdk/lua-5.4.2/linux" -L"../sdk/soloud/linux" -L"."
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS) -lfreetype -lX11 -lGL -lpthread -lpng -lstdc++fs -llua54 -ldl -lsoloud_static -lasound -lbox2d
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(CXX) -o $(TARGET) $(LINKOBJS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/game/src/animation.o \
	$(OBJDIR)/game/src/assets.o \
	$(OBJDIR)/game/src/coordinates.o \
	$(OBJDIR)/game/src/engine/src/olcPixelGameEngine.o \
	$(OBJDIR)/game/src/fonts.o \
	$(OBJDIR)/game/src/game.o \
	$(OBJDIR)/game/src/main.o \
	$(OBJDIR)/game/src/olcTemplate.o \
	$(OBJDIR)/game/src/render/helper/src/olcHelper.o \
	$(OBJDIR)/game/src/render/src/exampleCollisionRender.o \
	$(OBJDIR)/game/src/render/src/examplePathLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleScreenElementsLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleWalkLevelRender.o \
	$(OBJDIR)/game/src/render/src/introRender.o \
	$(OBJDIR)/game/src/render/src/levelRender.o \
	$(OBJDIR)/game/src/render/src/mainMenuRender.o \
	$(OBJDIR)/game/src/sound.o \
	$(OBJDIR)/game/src/state/src/exampleCollisionState.o \
	$(OBJDIR)/game/src/state/src/examplePathLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleScreenElementsLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleWalkLevelState.o \
	$(OBJDIR)/game/src/state/src/introState.o \
	$(OBJDIR)/game/src/state/src/levelState.o \
	$(OBJDIR)/game/src/state/src/mainMenuState.o \
	$(OBJDIR)/game/src/textbox.o \
	$(OBJDIR)/game/src/tools/src/fader.o \
	$(OBJDIR)/game/src/tools/src/pathfinding.o \
	$(OBJDIR)/game/src/tools/src/pathfollower.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl2.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl3.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_demo.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_draw.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_tables.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_widgets.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),test)
  OBJDIR              = obj/Test
  TARGETDIR           = bin/Test
  TARGET              = $(TARGETDIR)/OlcTemplate
  DEFINES            += -DRUN_TESTS
  INCLUDES           += -I".." -I"../sdk/box2d/include" -I"../sdk/imgui-1.90.4" -I"../sdk/imgui-1.90.4/backends" -I"../sdk/sol2-3.3.0" -I"../sdk/lua-5.4.2/include" -I"../sdk/soloud/include" -I"../sdk/freetype-2.13.1/include" -I"../../../../../usr/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -std=c++2a
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -std=c++2a
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../../../usr/lib" -L"../sdk/box2d/linux" -L"../sdk/lua-5.4.2/linux" -L"../sdk/soloud/linux" -L"."
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS) -lfreetype -lX11 -lGL -lpthread -lpng -lstdc++fs -llua54 -ldl -lsoloud_static -lasound -lbox2d
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(CXX) -o $(TARGET) $(LINKOBJS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/game/src/animation.o \
	$(OBJDIR)/game/src/assets.o \
	$(OBJDIR)/game/src/coordinates.o \
	$(OBJDIR)/game/src/engine/src/olcPixelGameEngine.o \
	$(OBJDIR)/game/src/fonts.o \
	$(OBJDIR)/game/src/game.o \
	$(OBJDIR)/game/src/main.o \
	$(OBJDIR)/game/src/olcTemplate.o \
	$(OBJDIR)/game/src/render/helper/src/olcHelper.o \
	$(OBJDIR)/game/src/render/src/exampleCollisionRender.o \
	$(OBJDIR)/game/src/render/src/examplePathLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleScreenElementsLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleWalkLevelRender.o \
	$(OBJDIR)/game/src/render/src/introRender.o \
	$(OBJDIR)/game/src/render/src/levelRender.o \
	$(OBJDIR)/game/src/render/src/mainMenuRender.o \
	$(OBJDIR)/game/src/sound.o \
	$(OBJDIR)/game/src/state/src/exampleCollisionState.o \
	$(OBJDIR)/game/src/state/src/examplePathLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleScreenElementsLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleWalkLevelState.o \
	$(OBJDIR)/game/src/state/src/introState.o \
	$(OBJDIR)/game/src/state/src/levelState.o \
	$(OBJDIR)/game/src/state/src/mainMenuState.o \
	$(OBJDIR)/game/src/textbox.o \
	$(OBJDIR)/game/src/tools/src/fader.o \
	$(OBJDIR)/game/src/tools/src/pathfinding.o \
	$(OBJDIR)/game/src/tools/src/pathfollower.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl2.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl3.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_demo.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_draw.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_tables.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_widgets.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR              = obj/Release
  TARGETDIR           = bin/Release
  TARGET              = $(TARGETDIR)/OlcTemplate
  DEFINES            +=
  INCLUDES           += -I".." -I".." -I"../sdk/box2d/include" -I"../sdk/imgui-1.90.4" -I"../sdk/imgui-1.90.4/backends" -I"../sdk/sol2-3.3.0" -I"../sdk/lua-5.4.2/include" -I"../sdk/soloud/include" -I"../sdk/freetype-2.13.1/include" -I"../../../../../usr/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -std=c++2a
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -std=c++2a
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../../../usr/lib" -L"../sdk/box2d/linux" -L"../sdk/lua-5.4.2/linux" -L"../sdk/soloud/linux" -L"." -s
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS) -lfreetype -lX11 -lGL -lpthread -lpng -lstdc++fs -llua54 -ldl -lsoloud_static -lasound -lbox2d
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(CXX) -o $(TARGET) $(LINKOBJS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/game/src/animation.o \
	$(OBJDIR)/game/src/assets.o \
	$(OBJDIR)/game/src/coordinates.o \
	$(OBJDIR)/game/src/engine/src/olcPixelGameEngine.o \
	$(OBJDIR)/game/src/fonts.o \
	$(OBJDIR)/game/src/game.o \
	$(OBJDIR)/game/src/main.o \
	$(OBJDIR)/game/src/olcTemplate.o \
	$(OBJDIR)/game/src/render/helper/src/olcHelper.o \
	$(OBJDIR)/game/src/render/src/exampleCollisionRender.o \
	$(OBJDIR)/game/src/render/src/examplePathLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleScreenElementsLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleWalkLevelRender.o \
	$(OBJDIR)/game/src/render/src/introRender.o \
	$(OBJDIR)/game/src/render/src/levelRender.o \
	$(OBJDIR)/game/src/render/src/mainMenuRender.o \
	$(OBJDIR)/game/src/sound.o \
	$(OBJDIR)/game/src/state/src/exampleCollisionState.o \
	$(OBJDIR)/game/src/state/src/examplePathLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleScreenElementsLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleWalkLevelState.o \
	$(OBJDIR)/game/src/state/src/introState.o \
	$(OBJDIR)/game/src/state/src/levelState.o \
	$(OBJDIR)/game/src/state/src/mainMenuState.o \
	$(OBJDIR)/game/src/textbox.o \
	$(OBJDIR)/game/src/tools/src/fader.o \
	$(OBJDIR)/game/src/tools/src/pathfinding.o \
	$(OBJDIR)/game/src/tools/src/pathfollower.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl2.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl3.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_demo.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_draw.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_tables.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_widgets.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR              = obj/x64/Debug
  TARGETDIR           = bin/Debug
  TARGET              = $(TARGETDIR)/OlcTemplate
  DEFINES            +=
  INCLUDES           += -I".." -I"../sdk/box2d/include" -I"../sdk/imgui-1.90.4" -I"../sdk/imgui-1.90.4/backends" -I"../sdk/sol2-3.3.0" -I"../sdk/lua-5.4.2/include" -I"../sdk/soloud/include" -I"../sdk/freetype-2.13.1/include" -I"../../../../../usr/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m64
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m64
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m64 -std=c++2a
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m64
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m64 -std=c++2a
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../../../usr/lib" -L"../sdk/box2d/linux" -L"../sdk/lua-5.4.2/linux" -L"../sdk/soloud/linux" -L"." -m64
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS) -lfreetype -lX11 -lGL -lpthread -lpng -lstdc++fs -llua54 -ldl -lsoloud_static -lasound -lbox2d
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(CXX) -o $(TARGET) $(LINKOBJS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/game/src/animation.o \
	$(OBJDIR)/game/src/assets.o \
	$(OBJDIR)/game/src/coordinates.o \
	$(OBJDIR)/game/src/engine/src/olcPixelGameEngine.o \
	$(OBJDIR)/game/src/fonts.o \
	$(OBJDIR)/game/src/game.o \
	$(OBJDIR)/game/src/main.o \
	$(OBJDIR)/game/src/olcTemplate.o \
	$(OBJDIR)/game/src/render/helper/src/olcHelper.o \
	$(OBJDIR)/game/src/render/src/exampleCollisionRender.o \
	$(OBJDIR)/game/src/render/src/examplePathLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleScreenElementsLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleWalkLevelRender.o \
	$(OBJDIR)/game/src/render/src/introRender.o \
	$(OBJDIR)/game/src/render/src/levelRender.o \
	$(OBJDIR)/game/src/render/src/mainMenuRender.o \
	$(OBJDIR)/game/src/sound.o \
	$(OBJDIR)/game/src/state/src/exampleCollisionState.o \
	$(OBJDIR)/game/src/state/src/examplePathLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleScreenElementsLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleWalkLevelState.o \
	$(OBJDIR)/game/src/state/src/introState.o \
	$(OBJDIR)/game/src/state/src/levelState.o \
	$(OBJDIR)/game/src/state/src/mainMenuState.o \
	$(OBJDIR)/game/src/textbox.o \
	$(OBJDIR)/game/src/tools/src/fader.o \
	$(OBJDIR)/game/src/tools/src/pathfinding.o \
	$(OBJDIR)/game/src/tools/src/pathfollower.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl2.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl3.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_demo.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_draw.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_tables.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_widgets.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),test64)
  OBJDIR              = obj/x64/Test
  TARGETDIR           = bin/Test
  TARGET              = $(TARGETDIR)/OlcTemplate
  DEFINES            += -DRUN_TESTS
  INCLUDES           += -I".." -I"../sdk/box2d/include" -I"../sdk/imgui-1.90.4" -I"../sdk/imgui-1.90.4/backends" -I"../sdk/sol2-3.3.0" -I"../sdk/lua-5.4.2/include" -I"../sdk/soloud/include" -I"../sdk/freetype-2.13.1/include" -I"../../../../../usr/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m64
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m64
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m64 -std=c++2a
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m64
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m64 -std=c++2a
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../../../usr/lib" -L"../sdk/box2d/linux" -L"../sdk/lua-5.4.2/linux" -L"../sdk/soloud/linux" -L"." -m64
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS) -lfreetype -lX11 -lGL -lpthread -lpng -lstdc++fs -llua54 -ldl -lsoloud_static -lasound -lbox2d
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(CXX) -o $(TARGET) $(LINKOBJS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/game/src/animation.o \
	$(OBJDIR)/game/src/assets.o \
	$(OBJDIR)/game/src/coordinates.o \
	$(OBJDIR)/game/src/engine/src/olcPixelGameEngine.o \
	$(OBJDIR)/game/src/fonts.o \
	$(OBJDIR)/game/src/game.o \
	$(OBJDIR)/game/src/main.o \
	$(OBJDIR)/game/src/olcTemplate.o \
	$(OBJDIR)/game/src/render/helper/src/olcHelper.o \
	$(OBJDIR)/game/src/render/src/exampleCollisionRender.o \
	$(OBJDIR)/game/src/render/src/examplePathLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleScreenElementsLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleWalkLevelRender.o \
	$(OBJDIR)/game/src/render/src/introRender.o \
	$(OBJDIR)/game/src/render/src/levelRender.o \
	$(OBJDIR)/game/src/render/src/mainMenuRender.o \
	$(OBJDIR)/game/src/sound.o \
	$(OBJDIR)/game/src/state/src/exampleCollisionState.o \
	$(OBJDIR)/game/src/state/src/examplePathLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleScreenElementsLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleWalkLevelState.o \
	$(OBJDIR)/game/src/state/src/introState.o \
	$(OBJDIR)/game/src/state/src/levelState.o \
	$(OBJDIR)/game/src/state/src/mainMenuState.o \
	$(OBJDIR)/game/src/textbox.o \
	$(OBJDIR)/game/src/tools/src/fader.o \
	$(OBJDIR)/game/src/tools/src/pathfinding.o \
	$(OBJDIR)/game/src/tools/src/pathfollower.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl2.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl3.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_demo.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_draw.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_tables.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_widgets.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR              = obj/x64/Release
  TARGETDIR           = bin/Release
  TARGET              = $(TARGETDIR)/OlcTemplate
  DEFINES            +=
  INCLUDES           += -I".." -I".." -I"../sdk/box2d/include" -I"../sdk/imgui-1.90.4" -I"../sdk/imgui-1.90.4/backends" -I"../sdk/sol2-3.3.0" -I"../sdk/lua-5.4.2/include" -I"../sdk/soloud/include" -I"../sdk/freetype-2.13.1/include" -I"../../../../../usr/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -m64
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -m64
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -m64 -std=c++2a
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -m64
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -m64 -std=c++2a
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../../../usr/lib" -L"../sdk/box2d/linux" -L"../sdk/lua-5.4.2/linux" -L"../sdk/soloud/linux" -L"." -s -m64
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS) -lfreetype -lX11 -lGL -lpthread -lpng -lstdc++fs -llua54 -ldl -lsoloud_static -lasound -lbox2d
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(CXX) -o $(TARGET) $(LINKOBJS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/game/src/animation.o \
	$(OBJDIR)/game/src/assets.o \
	$(OBJDIR)/game/src/coordinates.o \
	$(OBJDIR)/game/src/engine/src/olcPixelGameEngine.o \
	$(OBJDIR)/game/src/fonts.o \
	$(OBJDIR)/game/src/game.o \
	$(OBJDIR)/game/src/main.o \
	$(OBJDIR)/game/src/olcTemplate.o \
	$(OBJDIR)/game/src/render/helper/src/olcHelper.o \
	$(OBJDIR)/game/src/render/src/exampleCollisionRender.o \
	$(OBJDIR)/game/src/render/src/examplePathLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleScreenElementsLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleWalkLevelRender.o \
	$(OBJDIR)/game/src/render/src/introRender.o \
	$(OBJDIR)/game/src/render/src/levelRender.o \
	$(OBJDIR)/game/src/render/src/mainMenuRender.o \
	$(OBJDIR)/game/src/sound.o \
	$(OBJDIR)/game/src/state/src/exampleCollisionState.o \
	$(OBJDIR)/game/src/state/src/examplePathLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleScreenElementsLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleWalkLevelState.o \
	$(OBJDIR)/game/src/state/src/introState.o \
	$(OBJDIR)/game/src/state/src/levelState.o \
	$(OBJDIR)/game/src/state/src/mainMenuState.o \
	$(OBJDIR)/game/src/textbox.o \
	$(OBJDIR)/game/src/tools/src/fader.o \
	$(OBJDIR)/game/src/tools/src/pathfinding.o \
	$(OBJDIR)/game/src/tools/src/pathfollower.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl2.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl3.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_demo.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_draw.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_tables.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_widgets.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debuguniv64)
  AR         = libtool
  OBJDIR              = obj/Universal64/Debug
  TARGETDIR           = bin/Debug
  TARGET              = $(TARGETDIR)/OlcTemplate
  DEFINES            +=
  INCLUDES           += -I".." -I"../sdk/box2d/include" -I"../sdk/imgui-1.90.4" -I"../sdk/imgui-1.90.4/backends" -I"../sdk/sol2-3.3.0" -I"../sdk/lua-5.4.2/include" -I"../sdk/soloud/include" -I"../sdk/freetype-2.13.1/include" -I"../../../../../usr/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -arch x86_64 -arch ppc64
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -arch x86_64 -arch ppc64
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -arch x86_64 -arch ppc64 -std=c++2a
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -arch x86_64 -arch ppc64
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -arch x86_64 -arch ppc64 -std=c++2a
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../../../usr/lib" -L"../sdk/box2d/linux" -L"../sdk/lua-5.4.2/linux" -L"../sdk/soloud/linux" -L"." -arch x86_64 -arch ppc64
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS) -lfreetype -lX11 -lGL -lpthread -lpng -lstdc++fs -llua54 -ldl -lsoloud_static -lasound -lbox2d
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(CXX) -o $(TARGET) $(LINKOBJS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/game/src/animation.o \
	$(OBJDIR)/game/src/assets.o \
	$(OBJDIR)/game/src/coordinates.o \
	$(OBJDIR)/game/src/engine/src/olcPixelGameEngine.o \
	$(OBJDIR)/game/src/fonts.o \
	$(OBJDIR)/game/src/game.o \
	$(OBJDIR)/game/src/main.o \
	$(OBJDIR)/game/src/olcTemplate.o \
	$(OBJDIR)/game/src/render/helper/src/olcHelper.o \
	$(OBJDIR)/game/src/render/src/exampleCollisionRender.o \
	$(OBJDIR)/game/src/render/src/examplePathLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleScreenElementsLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleWalkLevelRender.o \
	$(OBJDIR)/game/src/render/src/introRender.o \
	$(OBJDIR)/game/src/render/src/levelRender.o \
	$(OBJDIR)/game/src/render/src/mainMenuRender.o \
	$(OBJDIR)/game/src/sound.o \
	$(OBJDIR)/game/src/state/src/exampleCollisionState.o \
	$(OBJDIR)/game/src/state/src/examplePathLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleScreenElementsLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleWalkLevelState.o \
	$(OBJDIR)/game/src/state/src/introState.o \
	$(OBJDIR)/game/src/state/src/levelState.o \
	$(OBJDIR)/game/src/state/src/mainMenuState.o \
	$(OBJDIR)/game/src/textbox.o \
	$(OBJDIR)/game/src/tools/src/fader.o \
	$(OBJDIR)/game/src/tools/src/pathfinding.o \
	$(OBJDIR)/game/src/tools/src/pathfollower.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl2.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl3.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_demo.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_draw.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_tables.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_widgets.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),testuniv64)
  AR         = libtool
  OBJDIR              = obj/Universal64/Test
  TARGETDIR           = bin/Test
  TARGET              = $(TARGETDIR)/OlcTemplate
  DEFINES            += -DRUN_TESTS
  INCLUDES           += -I".." -I"../sdk/box2d/include" -I"../sdk/imgui-1.90.4" -I"../sdk/imgui-1.90.4/backends" -I"../sdk/sol2-3.3.0" -I"../sdk/lua-5.4.2/include" -I"../sdk/soloud/include" -I"../sdk/freetype-2.13.1/include" -I"../../../../../usr/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -arch x86_64 -arch ppc64
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -arch x86_64 -arch ppc64
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -arch x86_64 -arch ppc64 -std=c++2a
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -arch x86_64 -arch ppc64
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -arch x86_64 -arch ppc64 -std=c++2a
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../../../usr/lib" -L"../sdk/box2d/linux" -L"../sdk/lua-5.4.2/linux" -L"../sdk/soloud/linux" -L"." -arch x86_64 -arch ppc64
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS) -lfreetype -lX11 -lGL -lpthread -lpng -lstdc++fs -llua54 -ldl -lsoloud_static -lasound -lbox2d
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(CXX) -o $(TARGET) $(LINKOBJS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/game/src/animation.o \
	$(OBJDIR)/game/src/assets.o \
	$(OBJDIR)/game/src/coordinates.o \
	$(OBJDIR)/game/src/engine/src/olcPixelGameEngine.o \
	$(OBJDIR)/game/src/fonts.o \
	$(OBJDIR)/game/src/game.o \
	$(OBJDIR)/game/src/main.o \
	$(OBJDIR)/game/src/olcTemplate.o \
	$(OBJDIR)/game/src/render/helper/src/olcHelper.o \
	$(OBJDIR)/game/src/render/src/exampleCollisionRender.o \
	$(OBJDIR)/game/src/render/src/examplePathLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleScreenElementsLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleWalkLevelRender.o \
	$(OBJDIR)/game/src/render/src/introRender.o \
	$(OBJDIR)/game/src/render/src/levelRender.o \
	$(OBJDIR)/game/src/render/src/mainMenuRender.o \
	$(OBJDIR)/game/src/sound.o \
	$(OBJDIR)/game/src/state/src/exampleCollisionState.o \
	$(OBJDIR)/game/src/state/src/examplePathLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleScreenElementsLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleWalkLevelState.o \
	$(OBJDIR)/game/src/state/src/introState.o \
	$(OBJDIR)/game/src/state/src/levelState.o \
	$(OBJDIR)/game/src/state/src/mainMenuState.o \
	$(OBJDIR)/game/src/textbox.o \
	$(OBJDIR)/game/src/tools/src/fader.o \
	$(OBJDIR)/game/src/tools/src/pathfinding.o \
	$(OBJDIR)/game/src/tools/src/pathfollower.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl2.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl3.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_demo.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_draw.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_tables.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_widgets.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),releaseuniv64)
  AR         = libtool
  OBJDIR              = obj/Universal64/Release
  TARGETDIR           = bin/Release
  TARGET              = $(TARGETDIR)/OlcTemplate
  DEFINES            +=
  INCLUDES           += -I".." -I".." -I"../sdk/box2d/include" -I"../sdk/imgui-1.90.4" -I"../sdk/imgui-1.90.4/backends" -I"../sdk/sol2-3.3.0" -I"../sdk/lua-5.4.2/include" -I"../sdk/soloud/include" -I"../sdk/freetype-2.13.1/include" -I"../../../../../usr/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -arch x86_64 -arch ppc64
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -arch x86_64 -arch ppc64
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -arch x86_64 -arch ppc64 -std=c++2a
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -arch x86_64 -arch ppc64
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -arch x86_64 -arch ppc64 -std=c++2a
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../../../usr/lib" -L"../sdk/box2d/linux" -L"../sdk/lua-5.4.2/linux" -L"../sdk/soloud/linux" -L"." -s -arch x86_64 -arch ppc64
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS) -lfreetype -lX11 -lGL -lpthread -lpng -lstdc++fs -llua54 -ldl -lsoloud_static -lasound -lbox2d
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(CXX) -o $(TARGET) $(LINKOBJS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/game/src/animation.o \
	$(OBJDIR)/game/src/assets.o \
	$(OBJDIR)/game/src/coordinates.o \
	$(OBJDIR)/game/src/engine/src/olcPixelGameEngine.o \
	$(OBJDIR)/game/src/fonts.o \
	$(OBJDIR)/game/src/game.o \
	$(OBJDIR)/game/src/main.o \
	$(OBJDIR)/game/src/olcTemplate.o \
	$(OBJDIR)/game/src/render/helper/src/olcHelper.o \
	$(OBJDIR)/game/src/render/src/exampleCollisionRender.o \
	$(OBJDIR)/game/src/render/src/examplePathLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleScreenElementsLevelRender.o \
	$(OBJDIR)/game/src/render/src/exampleWalkLevelRender.o \
	$(OBJDIR)/game/src/render/src/introRender.o \
	$(OBJDIR)/game/src/render/src/levelRender.o \
	$(OBJDIR)/game/src/render/src/mainMenuRender.o \
	$(OBJDIR)/game/src/sound.o \
	$(OBJDIR)/game/src/state/src/exampleCollisionState.o \
	$(OBJDIR)/game/src/state/src/examplePathLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleScreenElementsLevelState.o \
	$(OBJDIR)/game/src/state/src/exampleWalkLevelState.o \
	$(OBJDIR)/game/src/state/src/introState.o \
	$(OBJDIR)/game/src/state/src/levelState.o \
	$(OBJDIR)/game/src/state/src/mainMenuState.o \
	$(OBJDIR)/game/src/textbox.o \
	$(OBJDIR)/game/src/tools/src/fader.o \
	$(OBJDIR)/game/src/tools/src/pathfinding.o \
	$(OBJDIR)/game/src/tools/src/pathfollower.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl2.o \
	$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl3.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_demo.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_draw.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_tables.o \
	$(OBJDIR)/sdk/imgui-1.90.4/imgui_widgets.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJDIRS := \
	$(OBJDIR) \
	$(OBJDIR)/game/src \
	$(OBJDIR)/game/src/engine/src \
	$(OBJDIR)/game/src/render/helper/src \
	$(OBJDIR)/game/src/render/src \
	$(OBJDIR)/game/src/state/src \
	$(OBJDIR)/game/src/tools/src \
	$(OBJDIR)/sdk/imgui-1.90.4 \
	$(OBJDIR)/sdk/imgui-1.90.4/backends \

RESOURCES := \

.PHONY: clean prebuild prelink

all: $(OBJDIRS) $(TARGETDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LIBDEPS) $(EXTERNAL_LIBS) $(RESOURCES) $(OBJRESP) $(LDRESP) | $(TARGETDIR) $(OBJDIRS)
	@echo Linking OlcTemplate
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
	-$(call MKDIR,$(TARGETDIR))

$(OBJDIRS):
	@echo Creating $(@)
	-$(call MKDIR,$@)

clean:
	@echo Cleaning OlcTemplate
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH) $(MAKEFILE) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) -x c++-header $(DEFINES) $(INCLUDES) -o "$@" -c "$<"

$(GCH_OBJC): $(PCH) $(MAKEFILE) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_OBJCPPFLAGS) -x objective-c++-header $(DEFINES) $(INCLUDES) -o "$@" -c "$<"
endif

ifneq (,$(OBJRESP))
$(OBJRESP): $(OBJECTS) | $(TARGETDIR) $(OBJDIRS)
	$(SILENT) echo $^
	$(SILENT) echo $^ > $@
endif

ifneq (,$(LDRESP))
$(LDRESP): $(LDDEPS) | $(TARGETDIR) $(OBJDIRS)
	$(SILENT) echo $^
	$(SILENT) echo $^ > $@
endif

$(OBJDIR)/game/src/animation.o: ../game/src/animation.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/assets.o: ../game/src/assets.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/coordinates.o: ../game/src/coordinates.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/engine/src/olcPixelGameEngine.o: ../game/src/engine/src/olcPixelGameEngine.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/engine/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/fonts.o: ../game/src/fonts.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/game.o: ../game/src/game.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/main.o: ../game/src/main.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/olcTemplate.o: ../game/src/olcTemplate.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/render/helper/src/olcHelper.o: ../game/src/render/helper/src/olcHelper.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/render/helper/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/render/src/exampleCollisionRender.o: ../game/src/render/src/exampleCollisionRender.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/render/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/render/src/examplePathLevelRender.o: ../game/src/render/src/examplePathLevelRender.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/render/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/render/src/exampleScreenElementsLevelRender.o: ../game/src/render/src/exampleScreenElementsLevelRender.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/render/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/render/src/exampleWalkLevelRender.o: ../game/src/render/src/exampleWalkLevelRender.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/render/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/render/src/introRender.o: ../game/src/render/src/introRender.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/render/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/render/src/levelRender.o: ../game/src/render/src/levelRender.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/render/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/render/src/mainMenuRender.o: ../game/src/render/src/mainMenuRender.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/render/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/sound.o: ../game/src/sound.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/state/src/exampleCollisionState.o: ../game/src/state/src/exampleCollisionState.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/state/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/state/src/examplePathLevelState.o: ../game/src/state/src/examplePathLevelState.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/state/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/state/src/exampleScreenElementsLevelState.o: ../game/src/state/src/exampleScreenElementsLevelState.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/state/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/state/src/exampleWalkLevelState.o: ../game/src/state/src/exampleWalkLevelState.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/state/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/state/src/introState.o: ../game/src/state/src/introState.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/state/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/state/src/levelState.o: ../game/src/state/src/levelState.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/state/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/state/src/mainMenuState.o: ../game/src/state/src/mainMenuState.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/state/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/textbox.o: ../game/src/textbox.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/tools/src/fader.o: ../game/src/tools/src/fader.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/tools/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/tools/src/pathfinding.o: ../game/src/tools/src/pathfinding.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/tools/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/game/src/tools/src/pathfollower.o: ../game/src/tools/src/pathfollower.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/game/src/tools/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl2.o: ../sdk/imgui-1.90.4/backends/imgui_impl_opengl2.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/sdk/imgui-1.90.4/backends
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/sdk/imgui-1.90.4/backends/imgui_impl_opengl3.o: ../sdk/imgui-1.90.4/backends/imgui_impl_opengl3.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/sdk/imgui-1.90.4/backends
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/sdk/imgui-1.90.4/imgui.o: ../sdk/imgui-1.90.4/imgui.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/sdk/imgui-1.90.4
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/sdk/imgui-1.90.4/imgui_demo.o: ../sdk/imgui-1.90.4/imgui_demo.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/sdk/imgui-1.90.4
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/sdk/imgui-1.90.4/imgui_draw.o: ../sdk/imgui-1.90.4/imgui_draw.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/sdk/imgui-1.90.4
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/sdk/imgui-1.90.4/imgui_tables.o: ../sdk/imgui-1.90.4/imgui_tables.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/sdk/imgui-1.90.4
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/sdk/imgui-1.90.4/imgui_widgets.o: ../sdk/imgui-1.90.4/imgui_widgets.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/sdk/imgui-1.90.4
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
  -include $(OBJDIR)/$(notdir $(PCH))_objc.d
endif
